import type { AssetItem } from '@/types/assets';
import type { ExpenseItem } from '@/types/expenses';
import type { IncomeItem } from '@/types/incomes';
import type { LiabilityItem } from '@/types/liabilities';

export type NumberLike = number | null | undefined;

export function toSafeNumber(value: NumberLike): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : 0;
}

export function sumBy<T>(items: T[] | null | undefined, selector: (item: T) => NumberLike): number {
  if (!items?.length) return 0;

  return items.reduce((acc, item) => acc + toSafeNumber(selector(item)), 0);
}

export function calculateMonthlyCashflow(input: {
  activeIncome: NumberLike;
  passiveIncome: NumberLike;
  totalExpenses: NumberLike;
}): number {
  return toSafeNumber(input.activeIncome) + toSafeNumber(input.passiveIncome) - toSafeNumber(input.totalExpenses);
}

export function calculateNetWorth(input: { totalAssets: NumberLike; totalLiabilities: NumberLike }): number {
  return toSafeNumber(input.totalAssets) - toSafeNumber(input.totalLiabilities);
}

export function calculateFinancialFreedomPercentage(input: { passiveIncome: NumberLike; totalExpenses: NumberLike }): number {
  const totalExpenses = toSafeNumber(input.totalExpenses);
  if (totalExpenses <= 0) return 0;

  return (toSafeNumber(input.passiveIncome) / totalExpenses) * 100;
}

export function getIncomeNetMonthly(income: IncomeItem): number {
  return toSafeNumber(income.netMonthlyAmount ?? income.montoMensual);
}

export function getIncomeGrossMonthly(income: IncomeItem): number {
  return toSafeNumber(income.grossMonthlyAmount ?? income.incomeAmount ?? income.montoMensual);
}

export function getIncomeBreakdown(incomes: IncomeItem[] | null | undefined) {
  const activeIncome = sumBy(incomes, (income) => (income.sourceType === 'manual' ? getIncomeNetMonthly(income) : 0));
  const passiveIncome = sumBy(incomes, (income) => (income.sourceType === 'derived_asset' || income.incomeKind === 'ingreso_pasivo' ? getIncomeNetMonthly(income) : 0));
  const grossIncome = sumBy(incomes, getIncomeGrossMonthly);
  const netIncome = sumBy(incomes, getIncomeNetMonthly);
  const totalDeductions = sumBy(incomes, (income) => income.totalDeductionsMonthly);

  return { activeIncome, passiveIncome, grossIncome, netIncome, totalDeductions };
}

export function getFinancialMetrics(input: {
  assets: AssetItem[] | null | undefined;
  liabilities: LiabilityItem[] | null | undefined;
  incomes: IncomeItem[] | null | undefined;
  expenses: ExpenseItem[] | null | undefined;
}) {
  const totalAssets = sumBy(input.assets, (asset) => asset.valorActual);
  const totalLiabilities = sumBy(input.liabilities, (liability) => liability.saldoActual);
  const totalExpenses = sumBy(input.expenses, (expense) => expense.montoMensual);
  const { activeIncome, passiveIncome, grossIncome, netIncome, totalDeductions } = getIncomeBreakdown(input.incomes);

  const monthlyCashflow = calculateMonthlyCashflow({ activeIncome, passiveIncome, totalExpenses });
  const netWorth = calculateNetWorth({ totalAssets, totalLiabilities });
  const financialFreedomPercentage = calculateFinancialFreedomPercentage({ passiveIncome, totalExpenses });

  return {
    totalAssets,
    totalLiabilities,
    totalExpenses,
    activeIncome,
    passiveIncome,
    grossIncome,
    netIncome,
    totalDeductions,
    monthlyCashflow,
    netWorth,
    financialFreedomPercentage
  };
}

export function formatCurrency(value: NumberLike, currency = 'USD', locale = 'en-US'): string {
  return new Intl.NumberFormat(locale, { style: 'currency', currency, maximumFractionDigits: 0 }).format(toSafeNumber(value));
}

export function getAssetMonthlyIncome(asset: AssetItem): number {
  return asset.generaIngreso ? toSafeNumber(asset.ingresoMensual) : 0;
}

export function getAssetMonthlyExpense(asset: AssetItem): number {
  if (!asset.tieneGasto) return 0;
  return toSafeNumber(asset.gastoMensual);
}

export function getAssetCashFlow(asset: AssetItem): number {
  return getAssetMonthlyIncome(asset) - getAssetMonthlyExpense(asset);
}

export function getAssetRoi(asset: AssetItem): number {
  const value = toSafeNumber(asset.valorActual);
  if (value <= 0) return 0;
  return (getAssetCashFlow(asset) * 12 / value) * 100;
}

export function getAssetDebt(asset: AssetItem, liabilities: LiabilityItem[] | null | undefined): number {
  return sumBy(liabilities?.filter((liability) => liability.linkedAssetId === asset.id || liability.id === asset.linkedLiabilityId || liability.id === asset.autoGeneratedLiabilityId), (liability) => liability.saldoActual);
}

export function getPatrimonyExplanation(input: { totalAssets: NumberLike; totalLiabilities: NumberLike; productiveAssetCount: number }): string {
  const netWorth = calculateNetWorth({ totalAssets: input.totalAssets, totalLiabilities: input.totalLiabilities });
  const base = netWorth < 0 ? 'Tus pasivos superan tus activos.' : 'Tus activos superan tus obligaciones.';
  return input.productiveAssetCount > 0 ? `${base} Parte de tu patrimonio genera flujo.` : base;
}

export function getWealthMetrics(input: { assets: AssetItem[] | null | undefined; liabilities: LiabilityItem[] | null | undefined }) {
  const totalAssets = sumBy(input.assets, (asset) => asset.valorActual);
  const totalLiabilities = sumBy(input.liabilities, (liability) => liability.saldoActual);
  const productiveAssets = input.assets?.filter((asset) => asset.generaIngreso || asset.wealthClass === 'productivo') ?? [];
  const assetCashFlow = sumBy(input.assets, getAssetCashFlow);
  const assetExpenses = sumBy(input.assets, getAssetMonthlyExpense);
  const associatedDebt = sumBy(input.assets, (asset) => getAssetDebt(asset, input.liabilities));
  const generatedPatrimony = totalAssets - associatedDebt;
  const assetRoi = totalAssets > 0 ? (assetCashFlow * 12 / totalAssets) * 100 : 0;

  return {
    totalAssets,
    totalLiabilities,
    netWorth: calculateNetWorth({ totalAssets, totalLiabilities }),
    productiveAssetCount: productiveAssets.length,
    assetCashFlow,
    assetExpenses,
    associatedDebt,
    generatedPatrimony,
    assetRoi,
    explanation: getPatrimonyExplanation({ totalAssets, totalLiabilities, productiveAssetCount: productiveAssets.length })
  };
}
