import { FinancialEntityCard } from '@/components/ui/FinancialEntityCard';
import { getAssetCashFlow, getAssetMonthlyExpense, getAssetMonthlyIncome } from '@/lib/finance/metrics';
import type { AssetItem, AssetType, AssetWealthClass } from '@/types/assets';

type AssetCardProps = {
  asset: AssetItem;
  onEdit?: (asset: AssetItem) => void;
  onDelete?: (assetId: string) => void;
};

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat('es-MX', { month: 'short', day: '2-digit', year: 'numeric' });

const typeMeta: Record<AssetType, { label: string }> = {
  Cuenta: { label: 'Cuenta' },
  Inversión: { label: 'Inversión' },
  Propiedad: { label: 'Propiedad' },
  Vehículo: { label: 'Vehículo' },
  Cripto: { label: 'Cripto' },
  Acciones: { label: 'Acciones' }
};

const classLabel: Record<AssetWealthClass, string> = {
  apreciable: 'Apreciable',
  depreciable: 'Depreciable',
  liquido: 'Líquido',
  productivo: 'Productivo',
  no_productivo: 'No productivo'
};

const expenseTypeLabel: Record<string, string> = {
  mantenimiento: 'Mantenimiento',
  operativo: 'Operativo',
  financiero: 'Financiero'
};

function inferClass(asset: AssetItem): AssetWealthClass {
  if (asset.wealthClass) return asset.wealthClass;
  if (asset.generaIngreso) return 'productivo';
  if (asset.tipo === 'Cuenta') return 'liquido';
  if (asset.tipo === 'Vehículo') return 'depreciable';
  return asset.tipo === 'Propiedad' || asset.tipo === 'Inversión' || asset.tipo === 'Acciones' || asset.tipo === 'Cripto' ? 'apreciable' : 'no_productivo';
}

function formatAssetDate(value?: string) {
  if (!value) return null;
  const parsedDate = new Date(value);
  return Number.isNaN(parsedDate.getTime()) ? null : date.format(parsedDate);
}

function assetTags(asset: AssetItem, wealthClass: AssetWealthClass, monthlyExpense: number) {
  const tags = [asset.generaIngreso ? 'Productivo' : 'No productivo'];

  if (asset.valueTrend === 'aprecia' || asset.tipo === 'Propiedad' || asset.tipo === 'Inversión') tags.push('Largo plazo');
  if (asset.linkedLiabilityId || asset.hasLinkedDebt || asset.autoGeneratedLiabilityId) tags.push('Deuda vinculada');
  if (monthlyExpense > 0) tags.push(expenseTypeLabel[asset.gastoTipo ?? 'mantenimiento'] ?? 'Mantenimiento');
  if (wealthClass === 'liquido') tags.push('Líquido');

  return tags.slice(0, 4).map((label) => ({ label }));
}

export function AssetCard({ asset, onEdit, onDelete }: AssetCardProps) {
  const monthlyIncome = getAssetMonthlyIncome(asset);
  const monthlyExpense = getAssetMonthlyExpense(asset);
  const cashFlow = getAssetCashFlow(asset);
  const wealthClass = inferClass(asset);
  const formattedDate = formatAssetDate(asset.fecha);

  return (
    <FinancialEntityCard
      tone="asset"
      title={asset.nombre}
      subtitle={`${typeMeta[asset.tipo].label} · ${classLabel[wealthClass]}`}
      badges={[{ label: asset.generaIngreso ? 'Productivo' : 'No productivo', tone: asset.generaIngreso ? 'positive' : 'neutral' }]}
      kpiLabel="Valor actual"
      kpiValue={money.format(asset.valorActual || 0)}
      meta={[
        { label: 'Ingreso mensual', value: money.format(monthlyIncome), tone: monthlyIncome > 0 ? 'positive' : 'default' },
        { label: 'Gasto asociado', value: money.format(monthlyExpense), tone: monthlyExpense > 0 ? 'negative' : 'default' },
        { label: 'Cash flow', value: money.format(cashFlow), tone: cashFlow > 0 ? 'positive' : cashFlow < 0 ? 'negative' : 'default' },
        { label: 'Registro', value: formattedDate ?? '—' }
      ]}
      tags={assetTags(asset, wealthClass, monthlyExpense)}
      actions={[
        { label: 'Editar', onClick: () => onEdit?.(asset) },
        { label: 'Eliminar', onClick: () => onDelete?.(asset.id), destructive: true }
      ]}
      footer={asset.notas ? <span>{asset.notas}</span> : null}
    />
  );
}
