import { FinancialEntityCard } from '@/components/ui/FinancialEntityCard';
import type { LiabilityDebtClass, LiabilityItem } from '@/types/liabilities';

type LiabilityCardProps = {
  liability: LiabilityItem;
  onEdit?: (liability: LiabilityItem) => void;
  onDelete?: (liabilityId: string) => void;
};

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat('es-MX', { month: 'short', day: '2-digit', year: 'numeric' });
const debtClassLabel: Record<LiabilityDebtClass, string> = {
  deuda_buena: 'Deuda buena',
  deuda_mala: 'Deuda mala',
  deuda_neutral: 'Deuda neutral'
};

function debtClassTone(debtClass: LiabilityDebtClass) {
  if (debtClass === 'deuda_buena') return 'positive' as const;
  if (debtClass === 'deuda_mala') return 'negative' as const;
  return 'warning' as const;
}

export function LiabilityCard({ liability, onEdit, onDelete }: LiabilityCardProps) {
  const debtClass = liability.debtClass ?? (liability.linkedAssetId ? 'deuda_buena' : liability.tipo === 'Tarjeta de crédito' ? 'deuda_mala' : 'deuda_neutral');

  return (
    <FinancialEntityCard
      tone="liability"
      title={liability.nombre}
      subtitle={`${liability.tipo}${liability.isAutoGenerated ? ' · generado por activo' : ''}`}
      badges={[{ label: debtClassLabel[debtClass], tone: debtClassTone(debtClass) }]}
      kpiLabel="Saldo actual"
      kpiValue={money.format(liability.saldoActual)}
      kpiTone={debtClass === 'deuda_mala' ? 'negative' : 'default'}
      meta={[
        { label: 'Pago mensual', value: money.format(liability.pagoMensual), tone: 'warning' },
        { label: 'Próxima obligación', value: date.format(new Date(liability.proximaFechaPago)), tone: 'warning' },
        { label: 'Clasificación', value: debtClassLabel[debtClass], tone: debtClassTone(debtClass) },
        { label: 'Vínculo', value: liability.linkedAssetId ? 'Con activo' : 'Sin activo' }
      ]}
      tags={[
        { label: liability.generaGasto ? 'Gasto automático' : 'Sin gasto automático', tone: liability.generaGasto ? 'warning' : 'neutral' },
        { label: liability.linkedAssetId ? 'Activo vinculado' : 'Sin activo asociado' },
        { label: debtClassLabel[debtClass], tone: debtClassTone(debtClass) }
      ]}
      actions={[
        { label: 'Editar', onClick: () => onEdit?.(liability) },
        { label: 'Eliminar', onClick: () => onDelete?.(liability.id), destructive: true }
      ]}
    />
  );
}
