'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { getAssetRoi } from '@/lib/finance/metrics';
import { useCapitalStore } from '@/store/useCapitalStore';
import type { AssetExpenseType, AssetIncomeFrequency, AssetType, AssetValueTrend, AssetWealthClass } from '@/types/assets';
import type { LiabilityDebtClass, LiabilityItem } from '@/types/liabilities';
import { FormField, FormSelect } from './FormControls';

const assetTypes: AssetType[] = ['Cuenta', 'Inversión', 'Propiedad', 'Vehículo', 'Cripto', 'Acciones'];
const wealthClasses: AssetWealthClass[] = ['apreciable', 'depreciable', 'liquido', 'productivo', 'no_productivo'];
const valueTrends: AssetValueTrend[] = ['aprecia', 'deprecia', 'estable'];
const incomeFrequencies: AssetIncomeFrequency[] = ['semanal', 'quincenal', 'mensual', 'trimestral', 'anual', 'una_vez'];
const expenseTypes: AssetExpenseType[] = ['mantenimiento', 'operativo', 'financiero'];

const incomeFrequencyLabel: Record<AssetIncomeFrequency, string> = {
  semanal: 'Semanal',
  quincenal: 'Quincenal',
  mensual: 'Mensual',
  trimestral: 'Trimestral',
  anual: 'Anual',
  una_vez: 'Una vez'
};
const wealthLabel: Record<AssetWealthClass, string> = {
  apreciable: 'Apreciable',
  depreciable: 'Depreciable',
  liquido: 'Líquido',
  productivo: 'Productivo',
  no_productivo: 'No productivo'
};
const trendLabel: Record<AssetValueTrend, string> = {
  aprecia: 'Se aprecia',
  deprecia: 'Se deprecia',
  estable: 'Valor estable'
};

const money = (value: number) => `$${value.toLocaleString('en-US', { maximumFractionDigits: 0 })}`;

function toNumber(value: string) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

type AssetCreateFormState = {
  nombre: string;
  tipo: AssetType;
  valorActual: string;
  fecha: string;
  descripcion: string;
  wealthClass: AssetWealthClass;
  valueTrend: AssetValueTrend;
  futureEstimatedValue: string;
  purchaseValue: string;
  generaIngreso: boolean;
  ingresoMonto: string;
  ingresoFrecuencia: AssetIncomeFrequency;
  tieneGasto: boolean;
  gastoMensual: string;
  gastoTipo: AssetExpenseType;
  hasLinkedDebt: boolean;
  linkedLiabilityId: string;
  mortgageBalance: string;
  mortgagePayment: string;
  propertyTax: string;
  insurance: string;
  hoa: string;
  maintenance: string;
  vacancy: string;
  debtPaymentDate: string;
};

function inferWealthClass(tipo: AssetType, generaIngreso: boolean): AssetWealthClass {
  if (generaIngreso) return 'productivo';
  if (tipo === 'Cuenta') return 'liquido';
  if (tipo === 'Vehículo') return 'depreciable';
  if (tipo === 'Propiedad' || tipo === 'Inversión' || tipo === 'Acciones' || tipo === 'Cripto') return 'apreciable';
  return 'no_productivo';
}

function buildInitialState(currentAsset?: ReturnType<typeof useCapitalStore.getState>['assets'][number]): AssetCreateFormState {
  const realEstate = currentAsset?.realEstateProfile;
  return {
    nombre: currentAsset?.nombre ?? '',
    tipo: currentAsset?.tipo ?? 'Cuenta',
    valorActual: String(currentAsset?.valorActual ?? ''),
    fecha: currentAsset?.fecha ?? '',
    descripcion: currentAsset?.descripcion ?? '',
    wealthClass: currentAsset?.wealthClass ?? inferWealthClass(currentAsset?.tipo ?? 'Cuenta', currentAsset?.generaIngreso ?? false),
    valueTrend: currentAsset?.valueTrend ?? (currentAsset?.tipo === 'Vehículo' ? 'deprecia' : 'aprecia'),
    futureEstimatedValue: String(currentAsset?.futureEstimatedValue ?? ''),
    purchaseValue: String(currentAsset?.purchaseValue ?? realEstate?.purchaseValue ?? ''),
    generaIngreso: currentAsset?.generaIngreso ?? false,
    ingresoMonto: String(currentAsset?.ingresoMensual ?? realEstate?.monthlyRent ?? ''),
    ingresoFrecuencia: currentAsset?.ingresoFrecuencia ?? 'mensual',
    tieneGasto: currentAsset?.tieneGasto ?? Boolean(currentAsset?.gastoMensual),
    gastoMensual: String(currentAsset?.gastoMensual ?? ''),
    gastoTipo: currentAsset?.gastoTipo ?? 'mantenimiento',
    hasLinkedDebt: currentAsset?.hasLinkedDebt ?? Boolean(currentAsset?.linkedLiabilityId ?? currentAsset?.autoGeneratedLiabilityId),
    linkedLiabilityId: currentAsset?.linkedLiabilityId ?? '',
    mortgageBalance: String(realEstate?.mortgageBalance ?? ''),
    mortgagePayment: String(realEstate?.mortgagePayment ?? ''),
    propertyTax: String(realEstate?.propertyTaxMonthly ?? ''),
    insurance: String(realEstate?.insuranceMonthly ?? ''),
    hoa: String(realEstate?.hoaMonthly ?? ''),
    maintenance: String(realEstate?.maintenanceMonthly ?? ''),
    vacancy: String(realEstate?.vacancyMonthly ?? ''),
    debtPaymentDate: realEstate?.paymentDate ?? currentAsset?.fecha ?? ''
  };
}

function classifyDebt(form: AssetCreateFormState): LiabilityDebtClass {
  if (form.tipo === 'Propiedad' || form.wealthClass === 'productivo') return 'deuda_buena';
  if (form.tipo === 'Vehículo') return 'deuda_mala';
  return 'deuda_neutral';
}

export function AssetCreateForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const editId = searchParams.get('id');
  const addAsset = useCapitalStore((state) => state.addAsset);
  const updateAsset = useCapitalStore((state) => state.updateAsset);
  const addLiability = useCapitalStore((state) => state.addLiability);
  const updateLiability = useCapitalStore((state) => state.updateLiability);
  const liabilities = useCapitalStore((state) => state.liabilities);
  const currentAsset = useCapitalStore((state) => state.assets.find((item) => item.id === editId));
  const currentMonthlyExpenses = useCapitalStore((state) => state.expenses.reduce((total, expense) => total + (expense.montoMensual || 0), 0));
  const [form, setForm] = useState<AssetCreateFormState>(() => buildInitialState(currentAsset));

  useEffect(() => {
    if (currentAsset) setForm(buildInitialState(currentAsset));
  }, [currentAsset]);

  const realEstateExpense = form.tipo === 'Propiedad'
    ? toNumber(form.propertyTax) + toNumber(form.insurance) + toNumber(form.hoa) + toNumber(form.maintenance) + toNumber(form.vacancy)
    : 0;
  const projectedIncome = form.generaIngreso ? toNumber(form.ingresoMonto) : 0;
  const projectedExpense = form.tieneGasto ? Math.max(toNumber(form.gastoMensual), realEstateExpense) : 0;
  const assetValue = toNumber(form.valorActual);
  const futureValue = toNumber(form.futureEstimatedValue);
  const mortgageBalance = toNumber(form.mortgageBalance);
  const mortgagePayment = toNumber(form.mortgagePayment);
  const debtLiabilityId = currentAsset?.autoGeneratedLiabilityId ?? (form.hasLinkedDebt && mortgageBalance > 0 ? `lib-asset-${Date.now()}` : '');

  const impact = useMemo(() => {
    const temporaryAsset = { valorActual: assetValue, generaIngreso: form.generaIngreso, ingresoMensual: projectedIncome, tieneGasto: form.tieneGasto, gastoMensual: projectedExpense };
    return {
      cashFlow: projectedIncome - projectedExpense,
      activeExpense: projectedExpense,
      netWorthChange: assetValue - mortgageBalance,
      freedom: currentMonthlyExpenses > 0 ? (projectedIncome / currentMonthlyExpenses) * 100 : 0,
      roi: getAssetRoi(temporaryAsset as never),
      futureDelta: futureValue > 0 ? futureValue - assetValue : 0
    };
  }, [assetValue, currentMonthlyExpenses, form.generaIngreso, form.tieneGasto, futureValue, mortgageBalance, projectedExpense, projectedIncome]);

  const errors = {
    nombre: form.nombre.trim().length === 0,
    valorActual: assetValue < 0 || form.valorActual === '',
    fecha: form.fecha.trim().length === 0,
    ingresoMonto: form.generaIngreso && projectedIncome <= 0,
    gastoMensual: form.tieneGasto && projectedExpense <= 0,
    mortgage: form.hasLinkedDebt && mortgageBalance <= 0
  };
  const canSubmit = !Object.values(errors).some(Boolean);

  const submit = () => {
    if (!canSubmit) return;
    const assetId = currentAsset?.id ?? `ast-${Date.now()}`;
    const autoLiabilityId = form.hasLinkedDebt && mortgageBalance > 0 ? debtLiabilityId : undefined;
    const linkedLiabilityId = form.linkedLiabilityId || autoLiabilityId || null;
    const propertyExpense = form.tipo === 'Propiedad' ? realEstateExpense : undefined;
    const monthlyExpense = form.tieneGasto ? Math.max(toNumber(form.gastoMensual), propertyExpense ?? 0) : undefined;

    const payload = {
      id: assetId,
      nombre: form.nombre.trim(),
      tipo: form.tipo,
      valorActual: assetValue,
      fecha: form.fecha,
      descripcion: form.descripcion,
      wealthClass: form.wealthClass,
      valueTrend: form.valueTrend,
      futureEstimatedValue: futureValue > 0 ? futureValue : undefined,
      purchaseValue: toNumber(form.purchaseValue) > 0 ? toNumber(form.purchaseValue) : undefined,
      generaIngreso: form.generaIngreso,
      ingresoMensual: form.generaIngreso ? projectedIncome : undefined,
      ingresoFrecuencia: form.generaIngreso ? form.ingresoFrecuencia : undefined,
      ingresoFechaInicio: form.generaIngreso ? form.fecha : undefined,
      ingresoRelacionadoId: form.generaIngreso ? currentAsset?.ingresoRelacionadoId ?? `inc-${Date.now()}` : undefined,
      linkedLiabilityId,
      hasLinkedDebt: form.hasLinkedDebt,
      autoGeneratedLiabilityId: autoLiabilityId,
      tieneGasto: form.tieneGasto,
      gastoMensual: monthlyExpense,
      gastoTipo: form.tieneGasto ? form.gastoTipo : undefined,
      gastoRelacionadoId: form.tieneGasto ? currentAsset?.gastoRelacionadoId ?? `asset-exp-${Date.now()}` : undefined,
      realEstateProfile: form.tipo === 'Propiedad' ? {
        purchaseValue: toNumber(form.purchaseValue),
        currentValue: assetValue,
        monthlyRent: projectedIncome,
        mortgageBalance,
        mortgagePayment,
        propertyTaxMonthly: toNumber(form.propertyTax),
        insuranceMonthly: toNumber(form.insurance),
        hoaMonthly: toNumber(form.hoa),
        maintenanceMonthly: toNumber(form.maintenance),
        vacancyMonthly: toNumber(form.vacancy),
        paymentDate: form.debtPaymentDate || form.fecha
      } : undefined
    };

    if (currentAsset) updateAsset(payload);
    else addAsset(payload);

    if (form.hasLinkedDebt && mortgageBalance > 0 && autoLiabilityId) {
      const liabilityPayload: LiabilityItem = {
        id: autoLiabilityId,
        nombre: `Deuda de ${form.nombre.trim()}`,
        tipo: form.tipo === 'Propiedad' ? 'Hipoteca' : 'Préstamo',
        saldoActual: mortgageBalance,
        pagoMensual: mortgagePayment,
        frecuenciaPago: 'mensual',
        proximaFechaPago: form.debtPaymentDate || form.fecha,
        generaGasto: mortgagePayment > 0,
        linkedAssetId: assetId,
        categoria: form.wealthClass === 'productivo' ? 'productivo' : 'operativo',
        debtClass: classifyDebt(form),
        isAutoGenerated: true,
        gastoRelacionadoId: mortgagePayment > 0 ? `exp-${autoLiabilityId}` : undefined
      };
      if (currentAsset?.autoGeneratedLiabilityId && liabilities.some((item) => item.id === currentAsset.autoGeneratedLiabilityId)) updateLiability(liabilityPayload);
      else addLiability(liabilityPayload);
    }

    router.push('/assets');
  };

  return (
    <div className="create-asset-layout grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_340px]">
      <div className="min-w-0 space-y-4">
        <section className="create-form-section">
          <p className="create-section-title">Activo inteligente</p>
          <div className="create-field-grid mt-4">
            <FormField label="Nombre" value={form.nombre} onChange={(value) => setForm((state) => ({ ...state, nombre: value }))} required />
            <FormSelect label="Tipo de activo" value={form.tipo} onChange={(value) => setForm((state) => ({ ...state, tipo: value as AssetType, wealthClass: inferWealthClass(value as AssetType, state.generaIngreso) }))} options={assetTypes} />
            <FormSelect label="Clasificación patrimonial" value={form.wealthClass} onChange={(value) => setForm((state) => ({ ...state, wealthClass: value as AssetWealthClass }))} options={wealthClasses} getLabel={(value) => wealthLabel[value as AssetWealthClass]} />
            <FormSelect label="Comportamiento de valor" value={form.valueTrend} onChange={(value) => setForm((state) => ({ ...state, valueTrend: value as AssetValueTrend }))} options={valueTrends} getLabel={(value) => trendLabel[value as AssetValueTrend]} />
            <FormField label="Valor actual" type="number" value={form.valorActual} onChange={(value) => setForm((state) => ({ ...state, valorActual: value }))} required />
            <FormField label="Valor futuro estimado" type="number" value={form.futureEstimatedValue} onChange={(value) => setForm((state) => ({ ...state, futureEstimatedValue: value }))} />
            <FormField label="Valor compra" type="number" value={form.purchaseValue} onChange={(value) => setForm((state) => ({ ...state, purchaseValue: value }))} />
            <FormField label="Fecha" type="date" value={form.fecha} onChange={(value) => setForm((state) => ({ ...state, fecha: value, debtPaymentDate: state.debtPaymentDate || value }))} required />
            <FormField label="Notas" value={form.descripcion} onChange={(value) => setForm((state) => ({ ...state, descripcion: value }))} />
          </div>
        </section>

        <section className="create-form-section space-y-3">
          <p className="create-section-title">Flujo del activo</p>
          <Toggle checked={form.generaIngreso} icon="↗" title="Genera ingresos" description="Crea ingreso derivado automático y eventos de calendario." onChange={(checked) => setForm((state) => ({ ...state, generaIngreso: checked, wealthClass: checked ? 'productivo' : state.wealthClass }))} />
          {form.generaIngreso ? <div className="create-field-grid rounded-[18px] border border-emerald-500/20 bg-emerald-50/60 p-4"><FormField label={form.tipo === 'Propiedad' ? 'Renta mensual' : 'Ingreso mensual'} type="number" value={form.ingresoMonto} onChange={(value) => setForm((state) => ({ ...state, ingresoMonto: value }))} required /><FormSelect label="Frecuencia" value={form.ingresoFrecuencia} onChange={(value) => setForm((state) => ({ ...state, ingresoFrecuencia: value as AssetIncomeFrequency }))} options={incomeFrequencies} getLabel={(value) => incomeFrequencyLabel[value as AssetIncomeFrequency]} /></div> : null}
          <Toggle checked={form.tieneGasto} icon="↘" title="Tiene gastos" description="Crea gasto derivado automático en el cuadrante de gastos." onChange={(checked) => setForm((state) => ({ ...state, tieneGasto: checked }))} />
          {form.tieneGasto ? <div className="create-field-grid rounded-[18px] border border-rose-500/20 bg-rose-50/60 p-4"><FormField label="Gasto mensual" type="number" value={form.gastoMensual || String(realEstateExpense || '')} onChange={(value) => setForm((state) => ({ ...state, gastoMensual: value }))} required /><FormSelect label="Tipo de gasto" value={form.gastoTipo} onChange={(value) => setForm((state) => ({ ...state, gastoTipo: value as AssetExpenseType }))} options={expenseTypes} /></div> : null}
        </section>

        {form.tipo === 'Propiedad' ? (
          <section className="create-form-section">
            <p className="create-section-title">Real estate / Propiedad</p>
            <div className="create-field-grid mt-4">
              <FormField label="Valor actual" type="number" value={form.valorActual} onChange={(value) => setForm((state) => ({ ...state, valorActual: value }))} />
              <FormField label="Valor compra" type="number" value={form.purchaseValue} onChange={(value) => setForm((state) => ({ ...state, purchaseValue: value }))} />
              <FormField label="Renta mensual" type="number" value={form.ingresoMonto} onChange={(value) => setForm((state) => ({ ...state, ingresoMonto: value, generaIngreso: Number(value) > 0, wealthClass: Number(value) > 0 ? 'productivo' : state.wealthClass }))} />
              <FormField label="Mortgage balance" type="number" value={form.mortgageBalance} onChange={(value) => setForm((state) => ({ ...state, mortgageBalance: value, hasLinkedDebt: Number(value) > 0 }))} />
              <FormField label="Mortgage payment" type="number" value={form.mortgagePayment} onChange={(value) => setForm((state) => ({ ...state, mortgagePayment: value }))} />
              <FormField label="Property tax" type="number" value={form.propertyTax} onChange={(value) => setForm((state) => ({ ...state, propertyTax: value, tieneGasto: true }))} />
              <FormField label="Seguro" type="number" value={form.insurance} onChange={(value) => setForm((state) => ({ ...state, insurance: value, tieneGasto: true }))} />
              <FormField label="HOA" type="number" value={form.hoa} onChange={(value) => setForm((state) => ({ ...state, hoa: value, tieneGasto: true }))} />
              <FormField label="Mantenimiento" type="number" value={form.maintenance} onChange={(value) => setForm((state) => ({ ...state, maintenance: value, tieneGasto: true }))} />
              <FormField label="Vacancy" type="number" value={form.vacancy} onChange={(value) => setForm((state) => ({ ...state, vacancy: value, tieneGasto: true }))} />
              <FormField label="Fecha pago" type="date" value={form.debtPaymentDate} onChange={(value) => setForm((state) => ({ ...state, debtPaymentDate: value }))} />
            </div>
          </section>
        ) : null}

        <section className="create-form-section space-y-3">
          <p className="create-section-title">Deuda vinculada</p>
          <Toggle checked={form.hasLinkedDebt} icon="⚖" title="Tiene deuda vinculada" description="Crea o enlaza un pasivo y su gasto financiero automáticamente." onChange={(checked) => setForm((state) => ({ ...state, hasLinkedDebt: checked }))} />
          {form.hasLinkedDebt || form.linkedLiabilityId ? (
            <div className="create-field-grid">
              <FormSelect label="Pasivo existente" value={form.linkedLiabilityId} onChange={(value) => setForm((state) => ({ ...state, linkedLiabilityId: value, hasLinkedDebt: Boolean(value) || state.hasLinkedDebt }))} options={['', ...liabilities.map((item) => item.id)]} getLabel={(value) => (value ? liabilities.find((item) => item.id === value)?.nombre ?? value : 'Crear automático / sin vínculo')} />
              <FormField label="Balance deuda" type="number" value={form.mortgageBalance} onChange={(value) => setForm((state) => ({ ...state, mortgageBalance: value }))} />
              <FormField label="Pago mensual deuda" type="number" value={form.mortgagePayment} onChange={(value) => setForm((state) => ({ ...state, mortgagePayment: value }))} />
            </div>
          ) : null}
        </section>
      </div>

      <aside className="create-impact-panel lg:sticky lg:top-4 lg:self-start">
        <p className="text-[11px] font-extrabold uppercase tracking-[0.14em] text-white/62">Patrimonio inteligente</p>
        <p className="mt-2 text-sm leading-6 text-white/72">Se crearán automáticamente ingresos, gastos, pasivos y eventos derivados desde datos reales.</p>
        <div className="mt-5 space-y-3">
          <ImpactMetric label="Cash flow activo" value={impact.cashFlow} />
          <ImpactMetric label="Gasto activo" value={impact.activeExpense} />
          <ImpactMetric label="Deuda asociada" value={mortgageBalance} />
          <ImpactMetric label="Patrimonio generado" value={impact.netWorthChange} />
          <div className="create-impact-metric"><p className="text-xs font-semibold text-white/58">ROI estimado</p><p className="mt-1 text-2xl font-extrabold text-white">{impact.roi.toFixed(1)}%</p></div>
          <div className="create-impact-metric"><p className="text-xs font-semibold text-white/58">Valor futuro</p><p className="mt-1 text-2xl font-extrabold text-white">{money(futureValue || assetValue)}</p><p className="mt-1 text-xs text-white/58">Delta {money(impact.futureDelta)}</p></div>
        </div>
        <div className="mt-5 flex gap-2"><button type="button" className="ds-btn-secondary w-full" onClick={() => router.back()}>Volver</button><button type="button" className="ds-btn-primary w-full" onClick={submit} disabled={!canSubmit}>{currentAsset ? 'Guardar' : 'Crear'}</button></div>
      </aside>
    </div>
  );
}

function Toggle({ checked, icon, title, description, onChange }: { checked: boolean; icon: string; title: string; description: string; onChange: (checked: boolean) => void }) {
  return (
    <label className="create-toggle-card" data-checked={checked}>
      <span className="flex min-w-0 items-center gap-3"><span className="create-toggle-icon">{icon}</span><span><span className="block text-sm font-extrabold text-[#10170D]">{title}</span><span className="block text-xs font-medium text-[rgba(16,23,13,0.58)]">{description}</span></span></span>
      <input className="sr-only" type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />
      <span className="create-switch" aria-hidden />
    </label>
  );
}

function ImpactMetric({ label, value }: { label: string; value: number }) {
  return <div className="create-impact-metric"><p className="text-xs font-semibold text-white/58">{label}</p><p className="mt-1 text-2xl font-extrabold text-white">{money(value)}</p></div>;
}
