export type LiabilityType = 'Tarjeta de crédito' | 'Préstamo' | 'Hipoteca' | 'Leasing' | 'Impuesto';
export type LiabilityPaymentFrequency = 'semanal' | 'quincenal' | 'mensual' | 'trimestral' | 'anual';
export type LiabilityCategory = 'productivo' | 'consumo' | 'fiscal' | 'operativo';
export type LiabilityDebtClass = 'deuda_buena' | 'deuda_mala' | 'deuda_neutral';

export type LiabilityItem = {
  id: string;
  nombre: string;
  tipo: LiabilityType;
  saldoActual: number;
  pagoMensual: number;
  frecuenciaPago?: LiabilityPaymentFrequency;
  proximaFechaPago: string;
  generaGasto: boolean;
  linkedAssetId?: string | null;
  categoria?: LiabilityCategory;
  debtClass?: LiabilityDebtClass;
  isAutoGenerated?: boolean;
  notas?: string;
  gastoRelacionadoId?: string;
};
